version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.4.0
  aws-ecs: circleci/aws-ecs@0.0.8
jobs:
  lint:
    docker:
      - image: circleci/node:10.16
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: lint
          command: npm run lint
workflows:
  build-and-deploy:
    jobs:
      - lint
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL
          repo: duet-api
          region: AWS_DEFAULT_REGION
          tag: '${CIRCLE_SHA1}'
          extra-build-args: '--build-arg SENDGRID_API_KEY=$SENDGRID_API_KEY
          --build-arg AWS_S3_BUCKET_NAME=$AWS_S3_BUCKET_NAME'
          filters:
            branches:
              only: rm_aws_config
      - aws-ecs/deploy-service-update:
          requires:
            - aws-ecr/build-and-push-image
          aws-region: AWS_DEFAULT_REGION
          family: 'duet-website'
          cluster-name: 'duet-website-staging'
          service-name: 'duet-website-staging'
          container-image-name-updates: 'container=duet-api,image-and-tag=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/duet-api:${CIRCLE_SHA1}'
          filters:
            branches:
              only: rm_aws_config